/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2022-03-08 11:42:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_005fbk_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1646727164000L));
    _jspx_dependants.put("jar:file:/Users/aehobakk/marketTeam/Servers/apache-tomcat-9.0.46/wtpwebapps/ICT_MARKET/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Hahmlet:wght@200&family=Play:wght@400;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Hahmlet:wght@200&family=Play:wght@400;700&display=swap');\n");
      out.write("	\n");
      out.write("	html, body{height:100%}\n");
      out.write("	#wrapper{\n");
      out.write("		height: auto;\n");
      out.write("		min-height: 100%;\n");
      out.write("		padding-bottom: 193px;\n");
      out.write("	}\n");
      out.write("	body{\n");
      out.write("transition :0.5s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".sidenav{\n");
      out.write("	width:100px;\n");
      out.write("	border-radius: 5px;\n");
      out.write("	position: fixed;\n");
      out.write("	right:0;\n");
      out.write("	z-index:1; \n");
      out.write("	background: #dcdcdc;\n");
      out.write("	margin-top: -1px; \n");
      out.write("	margin-right: 120px;\n");
      out.write("	overflow-y: hidden;\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	height: 0;\n");
      out.write("	\n");
      out.write("	transition :0.5s;\n");
      out.write("}\n");
      out.write(".sidenav a{\n");
      out.write("	\n");
      out.write("	color: #212529;\n");
      out.write("	text-decoration: none;\n");
      out.write("	font-size: px;\n");
      out.write("	font-family: 'Play', sans-serif;\n");
      out.write("	display: block;\n");
      out.write("	padding: 8px 8px 8px 5px;\n");
      out.write("	margin-top: 7px; \n");
      out.write("	\n");
      out.write("	transition :0.3s;\n");
      out.write("}\n");
      out.write(".sidenav a:hover{\n");
      out.write("	color: #f1f1f1;\n");
      out.write("}\n");
      out.write("	\n");
      out.write("	#main {\n");
      out.write("	height: auto;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.main_head{\n");
      out.write("	padding: 70px;\n");
      out.write("	}\n");
      out.write("	.main_head h2{\n");
      out.write("	font-family: 'Play', sans-serif;\n");
      out.write("	font-weight: 700;\n");
      out.write("	}\n");
      out.write("	.main_head p {\n");
      out.write("	font-family: 'Play', sans-serif;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#main_div{\n");
      out.write("	position: relative;\n");
      out.write("	}\n");
      out.write("	#main_div .main_contain{\n");
      out.write("	position: absolute;\n");
      out.write("	left: 20%;\n");
      out.write("	margin-top: -50px;\n");
      out.write("	text-align: center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.main_contain{\n");
      out.write("	font-family: font-family: 'Hahmlet', serif;\n");
      out.write("	width: 60%;\n");
      out.write("	height: auto;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.line{\n");
      out.write("	width: 100%;\n");
      out.write("	height: 1px;\n");
      out.write("	background: #eee;\n");
      out.write("	margin-top: 30px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.recently{\n");
      out.write("	overflow: auto;\n");
      out.write("	border: 1px solid #ccc;\n");
      out.write("	margin-top: 10px;\n");
      out.write("	width: 100%;\n");
      out.write("	height: 450px;\n");
      out.write("	background-color: #dcdcdc;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.wts{\n");
      out.write("	width: 49%;\n");
      out.write("	text-align: center;\n");
      out.write("	position:sattic;\n");
      out.write("	margin-top: 5px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.line2{\n");
      out.write("	width: 1px;\n");
      out.write("	height: 100%;\n");
      out.write("	background: #eee;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.wtb{\n");
      out.write("	width: 49%;\n");
      out.write("	text-align: center;\n");
      out.write("	position:sattic;\n");
      out.write("	margin-top: 5px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	footer{\n");
      out.write("	font-size: 40%;\n");
      out.write("	height: 150px;\n");
      out.write("	position: relative;\n");
      out.write("  	bottom: 0px;\n");
      out.write("	\n");
      out.write("	}\n");
      out.write("	footer div{\n");
      out.write("	font-family: 'Play', sans-serif;\n");
      out.write("	margin-top: 5px;\n");
      out.write("	margin-left: 90px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("<title>ICT Market</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"wrapper\">\n");
      out.write("<!-- 세션에 아이디가 존재하지 않을 때 헤더 -->\n");
      out.write("<!-- <header class=\"p-3 border-bottom bg-white sticky-top\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("			<a href=\"/\" class=\"d-flex align-items-center mb-2 mb-lg-0 text-black text-decoration-none\">\n");
      out.write("				<h2 style=\"margin:0\">ICT MARKET</h2>\n");
      out.write("			</a>\n");
      out.write("			\n");
      out.write("			<ul class=\"nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0\"></ul>\n");
      out.write("	\n");
      out.write("			<div>\n");
      out.write("				<ul class=\"nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0\">\n");
      out.write("	           \n");
      out.write("					<form class=\"col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3\">\n");
      out.write("						<input type=\"search\" class=\"form-control\" placeholder=\"Search...\" aria-label=\"Search\">\n");
      out.write("					</form>\n");
      out.write("	\n");
      out.write("					<li><a href=\"#\" class=\"nav-link px-2 link-dark fw-bold\">Login</a></li>\n");
      out.write("					<li><a href=\"#\" class=\"nav-link px-2 link-dark fw-bold\">Sign-up</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</header> -->\n");
      out.write("\n");
      out.write("<!-- 세션에 아이디가 존재할 때 헤더 -->\n");
      out.write("<header class=\"p-3 border-bottom bg-white sticky-top\">\n");
      out.write("<div class=\"container\">\n");
      out.write("	<div class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("		<a href=\"/\" class=\"d-flex align-items-center mb-2 mb-lg-0 text-black text-decoration-none\">\n");
      out.write("			<h2 style=\"margin:0; font-family: 'Play', sans-serif; font-weight: 700;\">ICT MARKET</h2>\n");
      out.write("		</a>\n");
      out.write("		\n");
      out.write("		<ul class=\"nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0\"></ul>\n");
      out.write("\n");
      out.write("		<div>\n");
      out.write("			<ul class=\"nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0\">\n");
      out.write("           \n");
      out.write("				<form class=\"col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3\">\n");
      out.write("					<input type=\"search\" class=\"form-control\" placeholder=\"Search...\" aria-label=\"Search\">\n");
      out.write("				</form>\n");
      out.write("               \n");
      out.write("				<li>\n");
      out.write("					<a href=\"#\" class=\"nav-link px-2 link-dark fw-bold\">\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-layout-text-sidebar-reverse\" viewBox=\"0 0 16 16\">\n");
      out.write("							<path d=\"M12.5 3a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1h5zm0 3a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1h5zm.5 3.5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5zm-.5 2.5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1h5z\"/>\n");
      out.write("							<path d=\"M16 2a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2zM4 1v14H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h2zm1 0h9a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5V1z\"/>\n");
      out.write("						</svg>\n");
      out.write("					</a>\n");
      out.write("				</li>\n");
      out.write("               \n");
      out.write("				<li>\n");
      out.write("					<a href=\"#\" class=\"nav-link px-2 link-dark fw-bold\">\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-pencil-square\" viewBox=\"0 0 16 16\">\n");
      out.write("							<path d=\"M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z\"/>\n");
      out.write("							<path fill-rule=\"evenodd\" d=\"M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z\"/>\n");
      out.write("						</svg>\n");
      out.write("					</a>\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					<a href=\"#\" class=\"nav-link px-2 link-dark fw-bold heart\">\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\n");
      out.write("							<path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\n");
      out.write("						</svg>\n");
      out.write("					</a>\n");
      out.write("				</li>\n");
      out.write("				<li><a href=\"#\" class=\"nav-link px-2 link-dark fw-bold\">calmdownman</a></li>\n");
      out.write("				<div id=\"defaultNav\" class=\"dNav\">\n");
      out.write("					<a href=\"#\" id=\"profile\" style=\"padding: 15px\" onclick=\"openNav()\"> \n");
      out.write("					<img src=\"https://yt3.ggpht.com/ytc/AKedOLTi6w4E6985-QdVBbovBSsnCeTETyj0WomjM5IY8Q=s88-c-k-c0x00ffffff-no-rj\" alt=\"mdo\" width=\"32\" height=\"32\" class=\"rounded-circle\"/>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</header>\n");
      out.write("<!-- Header Menu(onclick main body->close-->\n");
      out.write("				<div id=\"mySidenav\" class=\"sidenav\">\n");
      out.write("					<a href=\"#\" class=\"text-center\">Profile</a>\n");
      out.write("					<a href=\"#\" class=\"text-center\">Sell</a>\n");
      out.write("					<a href=\"#\" class=\"text-center\">Logout</a>\n");
      out.write("            	</div>\n");
      out.write("<script>\n");
      out.write("	function openNav(){\n");
      out.write("		document.getElementById(\"mySidenav\").style.height=\"160px\";\n");
      out.write("		document.body.style.backgroundColor=\"rgba(0,0,0,0.4)\";\n");
      out.write("		document.getElementById(\"main\").style.filter=\"blur(3px)\";\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	function closeNav(){\n");
      out.write("		document.getElementById(\"mySidenav\").style.height=\"0px\";\n");
      out.write("		document.body.style.backgroundColor=\"white\";\n");
      out.write("		document.getElementById(\"main\").style.filter=\"blur(0)\";\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- main-->\n");
      out.write("<div id=\"main\" onclick=\"closeNav()\">\n");
      out.write("	<div class=\"main_head\">\n");
      out.write("		");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		\n");
      out.write("		</div>\n");
      out.write("		<div id=\"main_div\">\n");
      out.write("			<div class=\"main_contain\">\n");
      out.write("				<h6 class=\"text-center\" style=\"float:left; margin-top:6px; margin-left:10px;\">\n");
      out.write("				Recently thread\n");
      out.write("				</h6>\n");
      out.write("				<button type=\"button\" class=\"btn btn-sm\" style=\"float:right;\">+</button>\n");
      out.write("				<div class=\"line\"></div>\n");
      out.write("					<div class=\"recently\">\n");
      out.write("					\n");
      out.write("						<div class=\"wtb\" style=\"float:left;\">\n");
      out.write("						Want to Buy\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</div>\n");
      out.write("					\n");
      out.write("					<div class=\"line2\" style=\"float:left;\"></div>\n");
      out.write("					\n");
      out.write("						<div class=\"wts\" style=\"float:right;\">\n");
      out.write("						Want to Sell\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!--footer-->\n");
      out.write("<footer class=\"p-3 py-3 border-top\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("			<div>\n");
      out.write("				<h6>Customer Service</h6>\n");
      out.write("					<ul class=\"nav flex-column\">\n");
      out.write("						<li class=\"nav-item mb-2 text-muted\">1111-6666</li>\n");
      out.write("						<li class=\"nav-item mb-2 text-muted\">MON-FRI : 10:00 ~ 17:00</li>\n");
      out.write("						<li class=\"nav-item mb-2 text-muted\">LUNCH: 13:00 ~ 14:00</li>\n");
      out.write("						<li class=\"nav-item mb-2 text-muted\">SAT, SUN, HOLIDAY OFF</li>\n");
      out.write("					</ul>\n");
      out.write("			</div>\n");
      out.write("            \n");
      out.write("			<div>\n");
      out.write("				<h6>ICT MARKET</h6>\n");
      out.write("				<ul class=\"nav flex-column\">\n");
      out.write("					<li class=\"nav-item mb-2\">대표 : 6666 |</li>\n");
      out.write("					<li class=\"nav-item mb-2\"> 사업자등록번호 : 666666666</li>\n");
      out.write("					<li class=\"nav-item mb-2\">통신판매업 : 2022-01234</li>\n");
      out.write("					<li class=\"nav-item mb-2\">주소 : 서울특별시 마포구 서교동 353-4 첨담빌딩 7층</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("            \n");
      out.write("			<div>\n");
      out.write("				<ul class=\"nav flex-column\" style=\"font-size:10px\">\n");
      out.write("					<li class=\"nav-item mb-2\">Copyright © ICT MARKET 2022. All Rights Reserved.</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>        \n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("			");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /Main_bk.jsp(247,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<h2 class=\"text-center\">Welcome back<!--, ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("--></h2>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<h2 class=\"text-center\">Welcome to ICT Market!</h2>\n");
          out.write("				<p class=\"text-center\">Online Marketplace to Buy & Sell</p>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Main_bk.jsp(268,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems("");
      // /Main_bk.jsp(268,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("wtbpreview");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("							<tr>\n");
            out.write("								<td></td>\n");
            out.write("								<td></td>\n");
            out.write("								<td></td>\n");
            out.write("							</tr>\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /Main_bk.jsp(281,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems("");
      // /Main_bk.jsp(281,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("wtspreview");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("							<tr>\n");
            out.write("								<td></td>\n");
            out.write("								<td></td>\n");
            out.write("								<td></td>\n");
            out.write("							</tr>\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
